### PR TITLE
Update dependencies and remove unused ones

### LINKED ISSUE #173: Update of node sources
During build we can currently see a lot of warnings about old or deprecated:
the software still works fine but might stop working 

...
npm WARN deprecated email-templates@3.3.2: 📫 Please upgrade to v3.5.0+ of email-templates to get email previews in your browser in development environment <https://goo.gl/Amu9sh>
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN deprecated mongodb@1.4.40: Please upgrade to 2.2.19 or higher
npm WARN deprecated ejs@0.8.8: Critical security bugs fixed in 2.5.5
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated mongodb@2.1.8: Please upgrade to 2.2.19 or higher
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN lifecycle typechecker@2.0.8~preinstall: cannot run in wd %s %s (wd=%s) typechecker@2.0.8 node ./cyclic.js /tmp/node_modules/.staging/typechecker-677b4fa0
npm WARN lifecycle typechecker@2.0.8~preinstall: cannot run in wd %s %s (wd=%s) typechecker@2.0.8 node ./cyclic.js /tmp/node_modules/.staging/typechecker-e044d9c7

### PR DESCRIPTION
**Pull request by FlorianSW**
During this I also commited the package-lock.json file, which is recommended by npm guys. This pins our dependencies to specific versions.

Fixes #173

### CODE REVIEW

**Comment by digitaldan** [comment]
Thanks!  I notice a few major version increases in libraries, just curious how much of the system was tested, like email templates and other less obvious parts?  The reason I ask is the last time we upgraded all the packages, little things broke everywhere :-)

**Comment by FlorianSW** [comment]
I clicked through each view of the web frontend and tested all functionality I know (except OAuth2 apps itself, this would be something, which needs to be tested by someone who might have it setup locally already). I also haven't tested the stuff, that is not reachable from the frontend (e.g. the mentioned e-mail templates). So it might be good if someone else would be able to check all functions just to be save :)

**Comment by marziman** [comment]
@FlorianSW,

thats risky. As @digitaldan mentioned this can lead to serious issues.

Can we first have this longer running with some tests.

I can try it out these days.

**Comment by digitaldan** [comment]
@FlorianSW no worries, I will make sure I test the lesser used parts for this PR on my personal system.

**Comment by digitaldan** [comment]
[Cloud PR's](https://trello.com/c/Aoq5a7w1/20-cloud-prs)

**Pull request closed without merging**
