### PR TITLE
Require the old password when changing the password

### LINKED ISSUE #74: Old password not required on password change
Description:
 Password change should require the old password. Without the old password, an attacker who is able to execute an XSS attack (or with physical access to the computer) may be able to impersonate the user.

Steps to reproduce:
1. Authenticate.
2.  Go to <baseurl>/account
3. Enter the new password twice. Click on 'Change'. 
4. Observe that the password has been successfully changed.

Mitigation:
Asks users for their old password and verify it before changing the password.

More info: https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Require_Re-authentication_for_Sensitive_Features

**Note**:  It would be nice if there is a way to send security issues to openhab via an alternate communication channel (e.g. security@openhab.org). This avoids that attackers are able to get knowledge of more serious security issues before they are fixed.

### PR DESCRIPTION
**Pull request by FlorianSW**
Instead of assuming, that the logged in user is legitimated to change
the password of the logged in user, require the current password when changing
the password to make sure, that the user has control over the account.

Fixes #74

### CODE REVIEW

**Comment by digitaldan** [comment]
Hi @FlorianSW would you mind fixing the merge conflicts the have just popped up?

**Comment by marziman** [comment]
Hi @FlorianSW ,

+1
I tried to get my fork up to date ..to actually review the other PR and test all on my local and remote setup. Would be thankful if you can check the conflicts..

Thx & BR Mehmet

**Comment by digitaldan** [comment]
When I run this branch I am getting this error at startup

`error: uncaughtException: missing ) after argument list date=Tue Apr 25 2017 15:12:26 GMT+0000 (UTC), pid=26329, uid=1001, gid=1001, cwd=/home/openhabcloud/openhabcloud, execPath=/home/openhabcloud/.nvm/versions/node/v7.5.0/bin/node, version=v7.5.0, argv=[/home/openhabcloud/.nvm/versions/node/v7.5.0/bin/node, /home/openhabcloud/openhabcloud/app.js], rss=73703424, heapTotal=47804416, heapUsed=31553760, external=18327485, loadavg=[0.08837890625, 0.02197265625, 0.00537109375], uptime=9313810, trace=[column=16, file=vm.js, function=Object.exports.runInThisContext, line=73, method=exports.runInThisContext, native=false, column=28, file=module.js, function=Module._compile, line=543, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=580, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=488, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=447, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=439, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=498, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false, column=22, file=/home/openhabcloud/openhabcloud/app.js, function=, line=56, method=null, native=false, column=32, file=module.js, function=Module._compile, line=571, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=580, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=488, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=447, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=439, method=Module._load, native=false, column=10, file=module.js, function=Module.runMain, line=605, method=runMain, native=false, column=7, file=bootstrap_node.js, function=run, line=418, method=null, native=false], stack=[/home/openhabcloud/openhabcloud/routes/account.js:218,         },         ^, SyntaxError: missing ) after argument list,     at Object.exports.runInThisContext (vm.js:73:16),     at Module._compile (module.js:543:28),     at Object.Module._extensions..js (module.js:580:10),     at Module.load (module.js:488:32),     at tryModuleLoad (module.js:447:12),     at Function.Module._load (module.js:439:3),     at Module.require (module.js:498:17),     at require (internal/module.js:20:19),     at Object.<anonymous> (/home/openhabcloud/openhabcloud/app.js:56:22),     at Module._compile (module.js:571:32),     at Object.Module._extensions..js (module.js:580:10),     at Module.load (module.js:488:32),     at tryModuleLoad (module.js:447:12),     at Function.Module._load (module.js:439:3),     at Module.runMain (module.js:605:10),     at run (bootstrap_node.js:418:7)]`
```

**Comment by marziman** [comment]
@FlorianSW @digitaldan 
Hi why did you merge this in? I had some review comments and this seems not to work..

**Comment by marziman** [comment]
@FlorianSW ,

sorry the review feature of GitHub tricked me. I made a review since long..and was wondering why you didn't check this one. Since you made new PRs :-)
Can you please check if I am wrong with my test?

**Comment by FlorianSW** [comment]
Ah, and I already wrote an answer now saying, that there were no review comments :P

I'll check this asap and reply then! :)

**Comment by FlorianSW** [comment]
Hmm, I tried it and can reproduce your described problem :/ If you enter the old password in the change password dialog, you'll get the correct message, that this password is false (that was what I tested during development). However, if you use the old password to login, it will work, but not with the new password.

If I restart openhab-cloud I can login with my new, but not with my old password. I'll take a deeper look and will find out, where the problem is, however, IÄm not sure, how the policy here is: Should I revert this PR and propose a new PR with a fix or only create a new PR with the fix only? :)

Sorry, that I haven't found this problem earlier :(

**Comment by FlorianSW** [comment]
So, in fact, the problem you describe isn't introduced by this PR, the password change does not work with the parent commit, too, with the same described behaviour. So, I'll create a new PR to fix this :)

**Comment by marziman** [comment]
@FlorianSW
no worries! I had this reviewed early after your PR. Dont worry! Thanks for validating and correcting it.

**Pull request merged**
