### PR TITLE
Adding new config option that disables registration

### PR DESCRIPTION
**Pull request by ryanrdetzel**
If you're running your own instance you probably don't want others registering.

Small bug fix where the link was hardcoded to https://home.myopenhab.org.

### CODE REVIEW

**Comment by marziman** [comment]
hi @ryanrdetzel ,

I am reviewing this and give feedback this days. Thanks!

**Comment by kobelka** [comment]
Works for me

**Comment by digitaldan** [comment]
>I ve reviewed this PR and just recognized that you had an "older" code base. We ve removed the "bcrypt-nodejs" in the package.json and therefor its reference in the code needs to be out, too.
@marziman I'm not sure I understand, his changes are against an earlier revision, but that's ok, thats how revision control works, git will merge the changes unless there are conflicts.  Did I miss something else?

**Comment by digitaldan** [comment]
>you ve removed the home.myopenhab link which is not a bug actually. This works on your machine/instance now for sure, but will break the link for the myopenhab.org machine of the foundation.

Just for clarification, we prefer to use a "full proxy" host name, like home.myopenhab.org that does not require complex routes that try and match every possible URL on a OH instance, its very hard to keep this up to date, and in fact we probably don't have all the mappings even now. I would love to git rid of this, but there are too many legacy apps that use it.   By using a host name different then the main server we can blindly proxy the request to an OH server.

**Comment by marziman** [comment]
@digitaldan yes I know. This shouldn't be a problem and we can merge it. No the only thing was "bcrypt-nodejs", but this will be no problem for git :-)
I will wait for his feedback regarding the URL and will merge it in.

**Comment by digitaldan** [comment]
Hi @ryanrdetzel we have another PR that also tries to change the home URL, can you update your PR to make this configurable or at least take it out so we can do this in another branch?  Thanks

**Comment by marziman** [comment]
Tested and going to merge in

**Pull request merged**
