### PR TITLE
Director server for routing requests to a openHAB cloud server. 

### PR DESCRIPTION
**Pull request by digitaldan**
Incoming requests are authenticated, we then lookup which server has a user's OH connection and finally we send a 302 redirect back to route the request to that server. NGINX will transparently handle the redirect so the end client never actually sees the 302.

### CODE REVIEW

**Comment by marziman** [comment]
@digitaldan,

so I gonna review this one. Are you done or should I wait?

**Comment by digitaldan** [comment]
@marziman it's as ready as it's going to be.  It's a little complicated to test, but I run multiple versions of openhab-cloud on my machine and point NGINX to each,  so for example I run one for web requests on port 3000, 2 for load balancing OH connections on port 3001 and 3002, and finally I run the director app on port 3003.   Then my NGIX file looks like
```

upstream web-requests {
        server 127.0.0.1:3000;
}

upstream socket-requests {
	ip_hash;
        server 127.0.0.1:3001;
        server 127.0.0.1:3002;
}

upstream proxy-requests {
        server 127.0.0.1:3003;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name foo.com home.foo.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name home.foo.com;

    charset utf-8;

    access_log /var/log/nginx/home.openhab.org-access.log;
    error_log /var/log/nginx/home.openhab.org-error.log;
    client_max_body_size 300m;

    root /var/www/html;

    location ~ /.well-known {
      allow all;
    }

    location / {
	proxy_pass http://proxy-requests;
    	proxy_redirect off;
    	proxy_http_version 1.1;
    	proxy_set_header Host $host;
   	proxy_set_header X-Real-IP $remote_addr ;
    	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for ;
    	proxy_set_header X-Forwarded-Proto https;
        proxy_intercept_errors on;
  	error_page 301 302 307 = @handle_proxy;
    }	

location @handle_proxy {
    set $proxy_server '$upstream_http_location';
    proxy_pass $proxy_server;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr ;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for ;
    proxy_set_header X-Forwarded-Proto https;
 }
}
server {
    listen 443 ssl;
    server_name `foo.com;`

    charset utf-8;

    access_log /var/log/nginx/my.openhab.org-access.log;
    error_log /var/log/nginx/my.openhab.org-error.log;
    client_max_body_size 300m;

    root /var/www/html;

    location ~ /.well-known {
      allow all;
    }

location /css {
    alias  /home/openhabcloud/openhabcloud/public/css;
    }
location /js {
    alias /home/openhabcloud/openhabcloud/public/js;
    }
location /img {
    alias /home/openhabcloud/openhabcloud/public/img;
    }
location /bootstrap {
    alias /home/openhabcloud/openhabcloud/public/bootstrap;
    }
location /font-icons {
    alias /home/openhabcloud/openhabcloud/public/font-icons;
    }
location /fonts {
    alias /home/openhabcloud/openhabcloud/public/fonts;
    }
location /js-plugin {
    alias /home/openhabcloud/openhabcloud/public/js-plugin;
    }
location /downloads {
    alias /home/openhabcloud/openhabcloud/public/downloads;
    }

location ~ ^/(rest|images|static|rrdchart.png|chart|openhab.app|WebApp|CMD|cometVisu|proxy|greent|jquery|classicui|ui|basicui|doc|start|icon|habmin|remote|habpanel|ifttt/v1/actions/command){
    proxy_pass http://proxy-requests;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr ;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for ;
    proxy_set_header X-Forwarded-Proto https;
    proxy_intercept_errors on;
  error_page 301 302 307 = @handle_proxy;
}

location @handle_proxy {
    set $proxy_server '$upstream_http_location';
    proxy_pass $proxy_server;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr ;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for ;
    proxy_set_header X-Forwarded-Proto https;
}

location /socket.io {
    proxy_pass http://socket-requests;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr ;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for ;
    proxy_set_header X-Forwarded-Proto https;
}

location / {
    proxy_pass http://web-requests;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr ;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for ;
    proxy_set_header X-Forwarded-Proto https;
}

#error_page 404 /404.html;

# redirect server error pages to the static page /50x.html
#
#error_page 500 502 503 504 /50x.html;
#location = /50x.html {
#root html;
#}
}```

**Comment by marziman** [comment]
@digitaldan 
I just made a quick review and need to fully test it. But I understood what you ve done so far...
Can we combine this with my docker-compose activities and let nginx load balance?
I also made some experiments about loadbalancing and the nginx.conf for docker would be close to what you ve done. We would add there more node apps (app-1, app-2, app-3) ...
What do you think does this makes sense?

**Comment by digitaldan** [comment]
Just an FYI, I'm going to just leave this alone for awhile.  While we work on others parts of the system.  We can come back to this when we start talking about scaling again.

**Pull request closed without merging**
