### PR TITLE
Extract the mongo connection parts to it's own system module

### PR DESCRIPTION
**Pull request by FlorianSW**
This makes the mongodb connection more streamlined and standardized
in the whole app. it also makes testing and changes a bit more easy.

### CODE REVIEW

**Comment by digitaldan** [comment]
Thanks for this, there is a lot of this type of cleanup that is needed.  And again, thanks for writing tests!

**Comment by digitaldan** [comment]
Just FYI, I have this running and don't have any issues yet.

**Comment by marziman** [comment]
@FlorianSW I ve reviewed it and it looks pretty good. Also took a look into the tests.
But there is one change: Before there was no need to set a password for mongo db. Now app stops
with "MongoError: Authentication failed. ". This would also need a spot in the docs, cause before the behavior was different (if we change it aim fine). But you will need a working user and pw for mongo.
BR Mehmet

**Comment by digitaldan** [comment]
>Before there was no need to set a password for mongo db

This is still the case, remove the username and password fields instead of setting them blank.

**Comment by marziman** [comment]
@digitaldan thanks, I remember I ran into this before. But as mentioned we haven't  documented this anywhere. So this works fine. Merging it now.

**Pull request merged**
