### PR TITLE
Design changes to match openHAB

### PR DESCRIPTION
**Pull request by FlorianSW**
This is the try to get the design a bit more aligned with
openHAB. The new design parts are oriented on the designs of
openHAB2, however, they're not the same. Mostly the header and footer,
as well as the navbar, has changed in this commit. The rounded
elements are replaced by angular ones.

Signed-off-by: Florian Schmidt <florian.schmidt.welzow@t-online.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks @FlorianSW, I agree that some visual update would be a good thing.
Trying out your changes, I have a few remarks though (let's look at this screen):

bildschirmfoto 2017-05-01 um 17 12 12

- The black font with white links in the header nav bar and the footer isn't nice - the previous white text was imho a better choice. 
- The Login/Sign-up with grey background does not fit the rest of the design.
- The “Sign in” and “Register” buttons cannot be recognized as buttons at all (and as pure text they don’t align, which isn’t nice either).

**Comment by FlorianSW** [comment]
> The black font with white links in the header nav bar and the footer isn't nice - the previous white text was imho a better choice.
The problem with that is, that the links can't be recognized as such, until the user hovers the mouse over it, I would say thta this is more or less problematic. Would it probably be ok, if the font is completely white, but inks are underlined? The same for the header?

> The Login/Sign-up with grey background does not fit the rest of the design.
If you login, it will, at least in my opinion. It's the same design as for openhab, where unselected menu items has a white background, selected and hovered ones are gray. And the login/signup action/menu item is imho the selected menu item for the start page. Would it probably be an idea to simply remove the login / signup menu entry, if it's the only available one and already selected, as there's no other available action, anyway?

> The “Sign in” and “Register” buttons cannot be recognized as buttons at all
They've a similar design as openhab. I agree, that openhab has a more streamlined UI concept, as button actions are at the bottom right and left of a menu/widget, which isn't the case here in openhab-cloud. Probably we can make the button's have the same color as they currently have when hovered and a darker gray when they're hovered?

> and as pure text they don’t align, which isn’t nice either
If they're hovered, they align :P But yes, I agree, not when they're not hovered :)

**Comment by kaikreuzer** [comment]
> The problem with that is, that the links can't be recognized as such, until the user hovers the mouse over it, I would say thta this is more or less problematic. 

In general I agree, but in this situation the links are so irrelevant that they imho do not need to "stand out". If you insist that they should, I'd say that underlining might be an option, although not necessarily a nice one. Maybe a (very) light grey could make a distinction.

> If you login, it will, at least in my opinion

Sorry, I couldn't test the logged in version, so I cannot comment. But if you say that it fits there, fine for me.

> Would it probably be an idea to simply remove the login / signup menu entry, if it's the only available one and already selected, as there's no other available action, anyway?

Yes, this would probably make sense.

> similar design as openhab.

Which UI do you actually refer to as "openhab"? The Paper UI?

> Probably we can make the button's have the same color as they currently have when hovered and a darker gray when they're hovered?

Might work, yes!

**Comment by FlorianSW** [comment]
> Sorry, I couldn't test the logged in version, so I cannot comment. But if you say that it fits there, fine for me.

Yep, it looks something like this (the Items action is selected, as the page is currently viewed):
image

> In general I agree, but in this situation the links are so irrelevant that they imho do not need to "stand out". If you insist that they should, I'd say that underlining might be an option, although not necessarily a nice one. Maybe a (very) light grey could make a distinction.

Oh, I don't insist, I'll change it back to white, which is fine for me, too (as long as we can get rid of this grey :)).

> Yes, this would probably make sense.

Done!

> Which UI do you actually refer to as "openhab"? The Paper UI?

Sorry, yes, I mean the Paper UI :)

**Comment by kaikreuzer** [comment]
> Yep, it looks something like this (the Items action is selected, as the page is currently viewed)

Ok, then I see where this grey background comes from.
The menu in the screenshot looks a bit "detached" from the rest - imho it might look better if the grey and green boxes would directly end at the orange header bar, wdyt?

**Comment by FlorianSW** [comment]
Sounds like a good idea, let's see, how it looks :)

**Comment by FlorianSW** [comment]
Looks good:
image

**Comment by kaikreuzer** [comment]
I like it as well, thanks 👍

**Comment by marziman** [comment]
@FlorianSW I will check this later on and merge it in, if it is ok for all..

**Comment by FlorianSW** [comment]
@marziman I don't want to sound impatient, but had you a chance to take a look to this PR? It would be great to have it merged :D Thanks in advance!

**Comment by marziman** [comment]
@FlorianSW,
all good! I was little busy. Sorry for being late..

**Comment by FlorianSW** [comment]
Thanks for merging :)

**Pull request merged**
