### PR TITLE
Uses baseURL for home proxy hack, we really need to fix this the righ…

### LINKED ISSUE #34: Incorrect URL when listening for sitemap events
I have a switch that is used to hide a sitemap frame.  When clicking it though openhab-cloud it didn't work.
I received the following error message in my web console:

`Firefox can't establish a connection to the server at https://home.openhab.org/rest/sitemaps/events/0982595d-9132-4bb5-800b-bacf5925cf96?sitemap=test&pageid=test.1smarthome.js:1:18688`

h

I assume the address should be `home.myopenhab.org` rather than `home.openhab.org`

### PR DESCRIPTION
**Pull request by digitaldan**
…t way at some point.  Fixes #34

Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by tavalin** [comment]
Cheers @digitaldan any ideas when this fix will be deployed to my.openhab?

**Comment by digitaldan** [comment]
I will hopefully deploy it in the next hour

**Comment by tavalin** [comment]
Awesome, thanks!

**Comment by digitaldan** [comment]
deployed, let me know if this works for you or not.  Thanks!

**Comment by tavalin** [comment]
Yep, I'm no longer getting error messages in the web console and the frame disappears and reappears as expected 👍

**Pull request merged**
