### PR TITLE
Fix paging parameter (page/skip/limit) handling.

### LINKED ISSUE #222: Event Log shows only first page
Below the list of events, there are links to further pages of older events. If I click on one of the numbers, all that happens is that the page reloads.

### PR DESCRIPTION
**Pull request by maniac103**
Query parameters are present in req.query, req.params only contains
named parameters that are part of the actual URL.

This re-applies the changes of commit
34a09b6c3e12c6184f29898cdc10ac6e36ff13d3 which were accidentally dropped
in commit cea8d8f7333fdb8bf50d43953eaa0057fb391996.

Closes #222

### CODE REVIEW

**Comment by maniac103** [comment]
@marziman I assume you didn't intend to essentially revert #174 in #194, right?
@digitaldan Please consider this for next deployment.

**Comment by digitaldan** [comment]
@marziman I didn't get to approve #194, but it looks more then deployment code was committed.  Why is app.js, api.js, events.js and others modified?  I think we need to roll that commit back.  I would like to deploy this weekend, but i'm not sure what is committed at this point.

**Comment by maniac103** [comment]
@digitaldan The js file changes essentially revert #174 (added back in this PR) and #188. My guess is that this was a rebase/merge fail.

**Comment by marziman** [comment]
@digitaldan,

that was a failed rebase on my side. #194
only had k8s deployment and the „params.query“ change was nit intended.

If I see it correctly, the PR #245 of @maniac103 will re-apply only those small „params.query“ stuff.

So no need to revert the whole initial k8s deployment PR.

@maniac103 can you please let us know if I am correct? Than merging this PR will be enough.

BR Mehmet

**Comment by cweitkamp** [comment]
Great. Thank you all for fixing it.

**Comment by maniac103** [comment]
> If I see it correctly, the PR #245 of @maniac103 will re-apply those overwritten changes.

@marziman Not exactly. #188 still needs to be applied again; the broknness fixed by that one just isn't as obvious, as it only fixes a corner case.

**Comment by digitaldan** [comment]
ok, i will find some time today to apply #188 again and test.

**Pull request merged**
