### PR TITLE
Explain how to register a device and provide links to the apps

### LINKED ISSUE #51: In devices page, point user towards how to register a device
Using a myopenhab.org URL as an example... https://myopenhab.org/devices

If you have no registered devices, the page only says,
"You currently have no devices registered with openHAB Cloud."
It is not clear how a device becomes registered.  I believe some users (me included) would expect registration to be done the system that is taking the registration, the cloud instance web site in this case.  But counter-intuitively, registration instead is done from the device.  So it would help to nudge the user in the right direction for how to resolve the "no devices registered" problem that we know they are encountering when they see that message.

It would be better if it said something like,
"You currently have no devices registered with openHAB Cloud.  To register a device, set the remote URL, myopenhab.org username, and myopenhab.org password in the device's app.  The remote URL should be set to https://myopenhab.org."
...replacing the URL reference with whatever the proper base URL is for the particular cloud instance.

### PR DESCRIPTION
**Pull request by FlorianSW**
Instead of just saying, that no devices are registered in openHAB-cloud,
give an exaplanation how to register a device, too.

This commit also adds links to the apps in the play store and itunes app
store, which ids are configurable to provide a link to a custom build, if
the openHAB-cloud admin has one and/or want to provide it.

Fixes #51

### CODE REVIEW

**Comment by marziman** [comment]
The description is understandable and looks good! Thanks a lot!

**Comment by FlorianSW** [comment]
Hmm, I'm not sure about what is better, so I let the decision up to you :) This is the result, if the badges are in the same area as the device info(s).

Without a device registered yet:
image

With a registered device:
image

**Comment by digitaldan** [comment]
When it comes to UX, everyone has a different opinion :-)  Can you center the two buttons within that right hand pane (looking at bottom picture)?

**Comment by marziman** [comment]
@FlorianSW,

look good. Yeah I would only say to center the buttons in the last image. We can merge it than..ok?

**Comment by digitaldan** [comment]
>look good. Yeah I would only say to center the buttons in the last image. 

Yes, I think the css is the same, so something on the dom is pushing/pulling it to the left.

>We can merge it than..ok?

Yep, we need that and the conflicts to be resolved.

**Comment by marziman** [comment]
@FlorianSW if you would be so kind and resolve the conflicts, I would go to merge it.
Thanks! (Small note: I am more night active due to the Ramadan :-) )

**Comment by FlorianSW** [comment]
openhab

**Comment by marziman** [comment]
Merging! Fixes https://github.com/openhab/openhab-cloud/issues/51

**Comment by FlorianSW** [comment]
That was fast, thank you! :)

**Pull request merged**
