### PR TITLE
Specify HOST for express server to listen on #168

### PR DESCRIPTION
**Pull request by DerOetzi**
As I explained on issue #168 adding the possibility to specify the listen IP for the express server

### CODE REVIEW

**Comment by digitaldan** [comment]
thanks!

**Comment by digitaldan** [comment]
I needed to revert this as the default '0.0.0.0' was not working on my hosts, can you check that this will not break installations that don't specify a host and submit a new PR?

**Comment by DerOetzi** [comment]
Hi is there any error log? Because I tested 0.0.0.0 before sending this PR on several hosts and works fine for me!
I will have a look the next days.

**Comment by digitaldan** [comment]
There was not an error, but it was not listening on ports, If I have time this week I will try and reproduce it.

**Comment by DerOetzi** [comment]
@digitaldan I have created a new PR #190 for this issue. I have tried again on several hosts and both are working for me so perhaps you can do a check up and give me feedback

Thanks

**Pull request merged**
