### PR TITLE
Docker requires a full path on individually mapped files.

### PR DESCRIPTION
**Pull request by iwilliamson**
Signed-off-by: Ian Williamson <freezerburnt@gmail.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
Just out of curiosity, i assume this worked for the original author @jasonxh , and is working for others as well, so i wonder why it is not working now?  Did docker compose change something in recent releases ?

**Comment by jasonxh** [comment]
I'm also curious about what's not working. While docker itself has always required absolute paths for bind mount, in my memory docker-compose has always supported relative host paths (must be prefixed with `./` or `../`). The determination of file vs dir is made by looking at the source type. In case the source doesn't exist, it'll be treated as a dir by default I believe. @iwilliamson can you clarify what issue you ran into?

**Comment by iwilliamson** [comment]
I struggled for a long time with this and finally stumbled on this:

https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume

Now, the ${PWD} solved **MY** issue, but there could be something else going on that I don't understand.  According to one comment: 

```If you experience a directory being created in place of the file you are trying to mount, you have probably failed to supply a valid and absolute path. This is a common mistake with a silent and confusing failure mode.```

The change shouldn't adversely affect anything, but I'm wondering why it worked for the author in the first place if the statement above is true.

**Comment by jasonxh** [comment]
I find many conflicting and confusing answers in that SO thread. I suspect that might be due to changing behaviors of docker / docker-compose over time, and potentially differences in OS. @iwilliamson Can you share which version of docker and docker-compose you are using and what host OS you are running on?

I'm a bit hesitant about adding `${PWD}` for a few reasons:
- It changes the behavior slightly. While relative paths are relative to the location of the `docker-compose.yml` file, `${PWD}` is current working dir. The difference shows when someone runs docker-compose command from a different dir with `-f` option.
- I'm afraid it can open another can of worms like reported in this other [SO thread](https://stackoverflow.com/questions/41948232/docker-compose-wont-find-pwd-environment-variable).
- I couldn't find any official documentation supporting this difference in behavior.

I'm hoping to understand the root cause better before making a change. One different change I would suggest trying is to change the short mount syntax to long syntax, like this:
```yaml
volumes:
- type: bind
  source: ./config.json.template
  target: /opt/openhabcloud/config.json.template
```

This could potentially generate an error if the mount source doesn't exist instead of treating it as a dir, as explained here https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior

**Comment by iwilliamson** [comment]
As I said in the other pull request:  Sorry, I've been busy with my day job for a while and just getting back to this.

I'm not a docker/docker-compose master so you'll have to excuse my ignorance in places and I 100% defer to your opinion.  But to answer your questions:
1. I'm running on a recently updated version of Ubuntu:  ```Linux web.domain.ca 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```
2. Docker version:  ```Docker version 19.03.6, build 369ce74a3c```
3. Docker Compose: ```docker-compose version 1.17.1, build unknown```

And.....I am confused now.  To try and understand the previous behaviour I set the docker-compose.yml setting back to without the ${PWD} and rebuilt and run the container and it works fine.  There's clearly something that I'm missing here - permissions maybe?  I'll maybe try a clean reinstall and see if it happens again.

**Comment by iwilliamson** [comment]
I have to say, I think this change has died on the vine.  I have no idea why it fixed my problem in the first place.  I've rolled back the change, deleted all my images and containers and rebuilt the images and everything is fine.  I even went back to the original directory where I was having problems and rolled the change back - still works.

I guess you can feel free to close the PR - sorry for wasting your time!

**Pull request closed without merging**
